on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: slim

    steps:
      - uses: actions/checkout@v4

      - name: dependencies
        run: |
          apt update
          apt install -y docker.io

      - name: deploy image
        env:
          IMAGE: registry.lucalise.ca/mc-dashboard
        run: |
          docker build --pull -t "$IMAGE:latest" .
          docker push "$IMAGE:latest"
