[package]
name = "dashboard_k3s"
version = "0.2.0"
edition = "2024"

[dependencies]
storage = { path = "../dashboard_storage", package = "dashboard_storage" }
askama = "0.16.0"
k8s-openapi = { version = "0.28.0", features = ["v1_36"] }
kube = { version = "4.0.0", features = ["runtime", "ws"] }
serde = { workspace = true }
serde_yaml = "0.9.34"
serde_json = { workspace = true }
thiserror = { workspace = true }
thiserror-ext = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
